#!/usr/bin/env bash
# update-wow.sh -- fetch the latest server patches for your WoW 3.3.5a client. Linux / macOS.
#
# Put this file in your WoW folder (next to Wow.exe) and run it:   ./update-wow.sh
# Or from anywhere:                                                ./update-wow.sh /path/to/WoW
#
# It only downloads a file when your copy differs from the server's, so running it when nothing
# has changed costs one small request. Nothing else in your client is touched -- not your addons,
# not your settings, not your realmlist.

set -euo pipefail

MANIFEST_URL="${WOW_MANIFEST_URL:-https://wow.allahaema.net/files/patches.json}"

c_green=$'\033[32m'; c_yellow=$'\033[33m'; c_red=$'\033[31m'; c_dim=$'\033[2m'; c_off=$'\033[0m'
[[ -t 1 ]] || { c_green=; c_yellow=; c_red=; c_dim=; c_off=; }
ok()   { printf '  %sok%s    %s\n'   "$c_green"  "$c_off" "$*"; }
upd()  { printf '  %supdated%s %s\n' "$c_yellow" "$c_off" "$*"; }
err()  { printf '  %serror%s %s\n'   "$c_red"    "$c_off" "$*" >&2; }
dim()  { printf '%s%s%s\n' "$c_dim" "$*" "$c_off"; }

# --- find the WoW folder -----------------------------------------------------------------------
WOW="${1:-}"
if [[ -z "$WOW" ]]; then
    if [[ -f "./Wow.exe" ]]; then WOW="$PWD"
    elif [[ -f "$(dirname "$0")/Wow.exe" ]]; then WOW="$(cd "$(dirname "$0")" && pwd)"
    fi
fi
if [[ -z "$WOW" || ! -f "$WOW/Wow.exe" ]]; then
    err "could not find your WoW folder."
    echo "     Put this script next to Wow.exe and run it there, or pass the path:"
    echo "       ./update-wow.sh \"/home/you/Games/WoW 3.3.5a\""
    exit 1
fi
WOW="$(cd "$WOW" && pwd)"

# --- tools --------------------------------------------------------------------------------------
if   command -v curl >/dev/null; then DL() { curl -fsSL --retry 3 -o "$2" "$1"; }; GET() { curl -fsSL --retry 3 "$1"; }
elif command -v wget >/dev/null; then DL() { wget -qO "$2" "$1"; };                GET() { wget -qO- "$1"; }
else err "needs curl or wget installed."; exit 1; fi

if   command -v sha256sum >/dev/null; then SUM() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum    >/dev/null; then SUM() { shasum -a 256 "$1" | cut -d' ' -f1; }   # macOS
else err "needs sha256sum or shasum."; exit 1; fi

echo
echo "WoW folder: $WOW"
dim "manifest:   $MANIFEST_URL"
echo

MANIFEST="$(GET "$MANIFEST_URL")" || { err "could not reach the update server. Is it up?"; exit 1; }

# Parse without requiring jq or python: the manifest is generated by us and one object per line.
mapfile -t ROWS < <(printf '%s' "$MANIFEST" \
  | tr '{' '\n' | grep '"file"' \
  | sed -E 's/.*"file"[: ]*"([^"]+)".*"dest"[: ]*"([^"]+)".*"sha256"[: ]*"([^"]+)".*/\1|\2|\3/')
BASE="$(printf '%s' "$MANIFEST" | sed -nE 's/.*"base_url"[: ]*"([^"]+)".*/\1/p' | head -1)"
[[ -n "$BASE" ]] || BASE="$(dirname "$MANIFEST_URL")/patches/"

[[ ${#ROWS[@]} -gt 0 ]] || { err "manifest had no patches in it — nothing to do."; exit 1; }

changed=0
for row in "${ROWS[@]}"; do
    IFS='|' read -r file dest want <<< "$row"
    target="$WOW/$dest"
    if [[ -f "$target" ]] && [[ "$(SUM "$target")" == "$want" ]]; then
        ok "$dest"
        continue
    fi
    mkdir -p "$(dirname "$target")"
    tmp="$target.part"
    printf '  %s...%s downloading %s\n' "$c_dim" "$c_off" "$dest"
    DL "$BASE$file" "$tmp" || { err "download failed: $file"; rm -f "$tmp"; exit 1; }
    got="$(SUM "$tmp")"
    if [[ "$got" != "$want" ]]; then
        err "checksum mismatch on $file — the download is corrupt, not applying it."
        echo "     expected $want"
        echo "     got      $got"
        rm -f "$tmp"; exit 1
    fi
    # Replace only after the checksum passes, so an interrupted run can never leave a half
    # written MPQ that the client would load and choke on.
    mv -f "$tmp" "$target"
    upd "$dest"
    changed=$((changed+1))
done

echo
if [[ $changed -eq 0 ]]; then
    echo "Already up to date. Nothing downloaded."
else
    echo "Updated $changed file(s). Restart WoW if it is running."
fi
