#!/usr/bin/env bash
# selftest.sh -- run the ItemBrowser self-test against the generated database.
#
# Two parts, in two separate Lua states because they stub the client differently:
#
#   selftest-data.lua  the shipped rows and the filter engine, checked field by field against
#                      a fresh dump of item_template
#   selftest-ui.lua    UI.lua driven for real against widget stubs
#
# This complements `regen.sh`, it does not replace it. regen.sh proves the generated BYTES are
# what the database would produce; this proves the addon gives the right answers back after
# the client has parsed them, and that the window's wiring runs without indexing a nil.
#
# Nothing here writes to any database, or anywhere outside a temporary file.
#
# usage:  tools/selftest.sh [--rows FILE] [-- <extra itemdb.py args>]
#
#   --rows FILE   use an existing dump instead of taking a fresh one (skips the DB entirely)

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROWS=""
KEEP=1
EXTRA=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --rows)    ROWS="$2"; shift 2;;
        --)        shift; EXTRA=("$@"); break;;
        -h|--help) sed -n '2,20p' "$0"; exit 0;;
        *) echo "selftest.sh: unknown argument '$1' (use -- to pass args straight to itemdb.py)" >&2
           exit 1;;
    esac
done

# LuaJIT is a Lua 5.1 implementation, which is what the client runs. The system `lua` may be
# 5.3+, whose integer division and `#` semantics would make a pass here mean nothing.
LUA=""
for candidate in luajit lua5.1; do
    if command -v "$candidate" >/dev/null; then LUA="$candidate"; break; fi
done
[[ -n "$LUA" ]] || { echo "selftest.sh: needs luajit or lua5.1 on PATH" >&2; exit 1; }

if [[ -z "$ROWS" ]]; then
    ROWS="$(mktemp -t itembrowser-rows.XXXXXX.tsv)"
    KEEP=0
    echo "== dumping item_template (read-only)"
    python3 "$HERE/itemdb.py" --dump-rows "$ROWS" ${EXTRA[@]+"${EXTRA[@]}"}
fi
cleanup() { [[ $KEEP -eq 0 ]] && rm -f "$ROWS"; }
trap cleanup EXIT

echo
echo "== part 1: the shipped database and the filters"
"$LUA" "$HERE/selftest-data.lua" "$ROWS"

echo
echo "== part 2: the UI wiring"
"$LUA" "$HERE/selftest-ui.lua"
