#!/usr/bin/env bash
# selftest.sh -- run the ItemBrowser self-test against the generated database.
#
# Three parts. The two Lua ones run in separate states because they stub the client
# differently:
#
#   UI.xml             validated against the CLIENT's own Interface\FrameXML\UI.xsd, read
#                      straight out of its MPQ chain. WoW answers XML it dislikes by skipping
#                      the file in silence, which in game looks exactly like an addon that
#                      failed to load, so this is the cheapest real check there is.
#   selftest-data.lua  the shipped rows and the filter engine, checked field by field against
#                      a fresh dump of item_template
#   selftest-ui.lua    UI.lua, Tree.lua and Launcher.lua driven for real against widget stubs
#
# This complements `regen.sh`, it does not replace it. regen.sh proves the generated BYTES are
# what the database would produce; this proves the addon gives the right answers back after
# the client has parsed them, and that the window's wiring runs without indexing a nil.
#
# Nothing here writes to any database, or anywhere outside a temporary file.
#
# usage:  tools/selftest.sh [--rows FILE] [--client-data DIR] [-- <extra itemdb.py args>]
#
#   --rows FILE       use an existing dump instead of taking a fresh one (skips the DB)
#   --client-data DIR the client whose UI.xsd the layout is validated against

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDON="$(dirname "$HERE")/ItemBrowser"
CLIENT_DATA="/home/ali/games/wow-3.3.5a/ChromieCraft_3.3.5a/Data"
ROWS=""
EXTRA=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --rows)        ROWS="$2"; shift 2;;
        --client-data) CLIENT_DATA="$2"; shift 2;;
        --)            shift; EXTRA=("$@"); break;;
        -h|--help) sed -n '2,24p' "$0"; exit 0;;
        *) echo "selftest.sh: unknown argument '$1' (use -- to pass args straight to itemdb.py)" >&2
           exit 1;;
    esac
done

# LuaJIT is a Lua 5.1 implementation, which is what the client runs. The system `lua` may be
# 5.3+, whose integer division and `#` semantics would make a pass here mean nothing.
LUA=""
for candidate in luajit lua5.1; do
    if command -v "$candidate" >/dev/null; then LUA="$candidate"; break; fi
done
[[ -n "$LUA" ]] || { echo "selftest.sh: needs luajit or lua5.1 on PATH" >&2; exit 1; }

XSD="$(mktemp -t itembrowser-ui.XXXXXX.xsd)"
ROWS_TMP=""
cleanup() { rm -f "$XSD"; [[ -n "$ROWS_TMP" ]] && rm -f "$ROWS_TMP"; return 0; }
trap cleanup EXIT

echo "== part 1: the layout against the client's own UI.xsd"
if ! command -v xmllint >/dev/null; then
    echo "   !! no xmllint on PATH -- the layout XML was NOT VALIDATED" >&2
elif ! python3 "$HERE/uixsd.py" "$CLIENT_DATA" "$XSD"; then
    echo "   !! no readable client at $CLIENT_DATA -- the layout XML was NOT VALIDATED" >&2
else
    for xml in "$ADDON/UI.xml" "$ADDON/Data/Data.xml"; do
        xmllint --noout --schema "$XSD" "$xml"
    done
fi

echo
if [[ -z "$ROWS" ]]; then
    ROWS="$(mktemp -t itembrowser-rows.XXXXXX.tsv)"
    ROWS_TMP="$ROWS"
    echo "== dumping item_template (read-only)"
    python3 "$HERE/itemdb.py" --dump-rows "$ROWS" ${EXTRA[@]+"${EXTRA[@]}"}
    echo
fi

echo "== part 2: the shipped database and the filters"
"$LUA" "$HERE/selftest-data.lua" "$ROWS"

echo
echo "== part 3: the UI wiring"
"$LUA" "$HERE/selftest-ui.lua"
