-- GENERATED by client/addons/mod-item-browser/tools/itemdb.py -- do not hand-edit.
-- Change the generator (or the world DB) and re-run:  tools/regen.sh
-- Provenance. /ib status prints this; compare it before debugging a friend's
-- "my results look different" report.
ItemBrowserData.build = {
  rows = 46098,
  icons = 4851,
  shards = 8,
  digest = "c7a54f1d98e78766",
}
